### ISSUE TITLE
Find method doesn't set the index to be searched before callbacks are run.

### ISSUE THREAD

**Issue by phongamus** [chujunlu/Array-methods#1]
Your Find method doesn't set the index to be searched before callbacks are run. Therefore if the callback adds an item to the array, your index to be searched expands (it should not).  The following test doesn't work.

'It should set the range of indexes to be run before any callbacks are run.\
    Items added to array by callback are not run by callback': function(){
      var array = [1,2,3];
      var counter = 0;
      var result = find(array, function(item,index){
        if (index <2){
          array.push(item);
          }
        counter+=1;
      })
      eq(counter, 3);
    }

**Comment by chujunlu** [comment]
> Your Find method doesn't set the index to be searched before callbacks are run. Therefore if the callback adds an item to the array, your index to be searched expands (it should not). The following test doesn't work.
> 
> 'It should set the range of indexes to be run before any callbacks are run.
> Items added to array by callback are not run by callback': function(){
> var array = [1,2,3];
> var counter = 0;
> var result = find(array, function(item,index){
> if (index <2){
> array.push(item);
> }
> counter+=1;
> })
> eq(counter, 3);
> }

You're right. Thanks for pointing that out Phong! I added this case to my code.
